apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: web
          image: ca-toronto-1.ocir.io/yzddwpsan8mt/catalogue-web:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb+srv://arbi:nouran@cluster0.ezcj5f4.mongodb.net/catalogue?retryWrites=true&w=majority"

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 5000